### PR TITLE
Added liquidPlacement logger

### PR DESCRIPTION
**Pull request by luisch444**
Simple logger for decoration of liquids. Mainly made by [angarn](https://github.com/zAngarn), I just remarked some parts and optimize the code. 

Useful when you are working with async lines and chunk swaps.

```
/log liquidPlacement
/carpet logLiquidPlacementMinHeight [int]
/carpet logLiquidPlacementMaxHeight [int]
```
## Showcase
- Example with logLiquidPlacementMinHeight 64 and logLiquidPlacementMaxHeight 70

### CODE REVIEW

**Review by Earthcomputer — COMMENTED** [review]
Code looks fine, however the logger could have a more descriptive name. At first glance I thought this was about placing liquids with a bucket. Waterfall placement maybe?

**Comment by luisch444** [comment]
That is a good point, what do you think about liquidGeneration? or maybe liquidPopulation?

**Comment by Earthcomputer** [comment]
Both work fine :+1:

**Comment by luisch444** [comment]
So I renamed liquidPlacement to liquidPopulation, all the commands are the same with the name modified.


```
/log liquidPopulation
/carpet logLiquidPopulationMinHeight [int]
/carpet logLiquidPopulationMaxHeight [int]
```

**Comment by Angarn** [comment]
Will this get merged at some point? This is really needed for falling block setups...

**Comment by Crec0** [comment]
This PR only logs overworld liquid population. Missing logger in `ChunkGeneratorHell#populate` (or other relevant places to include nether)
IMO nether population should also be logged since falling block setups are also done in nether. Although they usually use a radiator-like setup, liquid placement knowledge is still useful.

**Pull request closed without merging**
