### PR TITLE
/autosave command added

### PR DESCRIPTION
**Pull request by BattyBoopers**
Hi Gnembon,
I added just another useful command for carpet. Some examples:
`/autosave info` queries information about the autosave interval.
`/autosave detect 0 100` will only succeed if it was called at the autosave or the following 100 gameticks
`/autosave detect 0 100 run /any command you like` will additionally run `/any command you like` on success
`/autosave detect -10 10` will succeed only if it is called ten ticks before the autosave, ten gamticks after or anywhere in between.
`/autosave detect 890 10` is identical to the previous example

### CODE REVIEW

**Comment by gnembon** [comment]
Sorry for late response - I was away. While I don't feel like this command is needed (in carpet save-X commands can be run from commandblock so every scenario should be reproduceable using vanilla save-Xs), I am not against it either. one question I have regarding the modified 1.12.json url. They both resolve, yet their content is different pointing into a different resource locations. Is the previous one wrong and if so why?

**Comment by BattyBoopers** [comment]
I should have paid more attention to that. I didn't change anything in 1.12.json myself. Looks to me like that file gets overwritten each time you run ./gradlew setupCarpetmod. Why is it even in the repository?

**Comment by BattyBoopers** [comment]
What do you mean with your statement about the save-X commands? The /autosave command as implemented here has nothing in common with those and I don't see how I would use any of the vanilla commands as an autosave-detector, which is the main purpose of this command.

**Comment by gnembon** [comment]
please revert that 1.12.json changes, so I can merge it.

**Comment by BattyBoopers** [comment]
Okay, I reverted that change. But you may want to change the build system to not overwrite the file each time you run 'gradlew setupCarpetmod', it doesn't really make much sense to have a file in the repo that gets overwritten automatically all the time.

**Pull request merged**
